### ISSUE TITLE
Set certificate with Environment var

### ISSUE THREAD

**Issue by svrooij** [nodeintegration/rancher-haproxy#2]
I'm trying to create a custom Rancher catalog for our self. That would contain some (hopefully all) docker apps as templates for the catalog.

You can add this by adding [this](https://github.com/Fontys-Hogeschool-ICT/rancher-catalog.git) url as catalog. I made some questions to supply the certificate and the rest of the settings. But I cannot set metadata from the answers. I can however set Environment vars from the questions. So the complete certificate is set to `SSL_CERT` but I've got no way to import it into the container.

Do you have any ideas on how to solve this?
I was thinking off doing something like `echo ${SSL_CERT} > ${HAPROXY_SSL_CERT}`, would that work? 

The could you add this after [L21 in docker-entry.sh](https://github.com/nodeintegration/rancher-haproxy/blob/master/docker-entrypoint.sh#L21)

```
elif [[ -v SSL_CERT]]; then
      echo "[INFO]: Copy env cert to file"
      echo ${SSL_CERT} > ${HAPROXY_SSL_CERT}
```

**Comment by mrproper** [comment]
I actually created a catalog entry for rancher-haproxy thats waiting for merging to the community catalog, you can see the diff here if you want to duplicate a working catalog for it: https://github.com/rancher/community-catalog/pull/451

In that you'll see that there's a question in the catalog for SSL_CERT and SSL_KEY that is then referenced in the rancher-compose.yml metadata, last i checked this worked. Are you saying that doesnt work?

I have the cert and key separated but haproxy wants them combined, i wanted them separated in the compose as one may come from a different mechanism etc.

The reason i used the rancher metadata was originally because handling ssl certs in environment variable was problematic with the newline preservation, not to mention less secure. 

Im glad to see someone else is using this piece of software, I noticed you've got your own image of svrooij/rancher-haproxy-auto, im interested to hear if youv've made any changes that i can merge back into my one?

Cheers!

**Comment by svrooij** [comment]
Thanks for the update!

Have you actually tested this?
When I try your catalog entry, I got the following error:

```
5/4/2017 10:36:31 AM[INFO]: setting SYSLOG_FACILITY to: daemon
5/4/2017 10:36:31 AM[INFO]: ssl enabled...configuring
5/4/2017 10:36:31 AM[INFO]: getting base64 encoded ssl certificate from metadata http://rancher-metadata.rancher.internal/2015-12-19/self/service/metadata/ssl_cert
5/4/2017 10:36:31 AM[INFO]: getting base64 encoded ssl key from metadata http://rancher-metadata.rancher.internal/2015-12-19/self/service/metadata/ssl_key
5/4/2017 10:36:31 AM[INFO]: enabling ssl
5/4/2017 10:36:31 AM[INFO]: substituting ssl certificate
5/4/2017 10:36:31 AM[INFO]: enabling haproxy stats on port: 1936
5/4/2017 10:36:31 AM[DEBUG]: /usr/local/etc/haproxy/haproxy-backends.cfg contents:
5/4/2017 10:36:31 AM
5/4/2017 10:36:31 AMbackend nodered
5/4/2017 10:36:31 AM  mode http
5/4/2017 10:36:31 AM  server nodered-ddeca15a-80f3-45fd-9085-e036782a0307 10.42.120.150:1880
5/4/2017 10:36:31 AM[ALERT] 123/083631 (27) : parsing [/usr/local/etc/haproxy/haproxy.cfg:51] : 'bind *:443' : unable to load SSL private key from PEM file '/usr/local/etc/haproxy/server.pem'.
```

**Comment by mrproper** [comment]
If you check version 0.6.5, i have resolved that issue, it was concatting the cert and key with no line return, in my tests i must have had an extra line after the cert in the yaml which passed. Sorry about that!
